version: '2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8080:8080
        restart: always

    host1:
        depends_on:
            - reverseproxy
        # image: nginx:alpine
        # image: quay.io/whoacademy/virtual-learning-assistant
        # command: ./bp -p
        build: ./bot
        # mem_limit: 512m
        # mem_reservation: 128M
        # cpus: 1
        restart: always

    host2:
        depends_on:
            - reverseproxy
        # image: httpd:alpine
        # image: quay.io/whoacademy/virtual-learning-assistant
        # command: ./bp -p
        build: ./bot
        # mem_limit: 512m
        # mem_reservation: 128M
        # cpus: 1
        restart: always

    host3:
        depends_on:
            - reverseproxy
        # image: httpd:alpine
        # image: quay.io/whoacademy/virtual-learning-assistant
        # command: ./bp -p
        build: ./bot
        # mem_limit: 512m
        # mem_reservation: 128M
        # cpus: 1
        restart: always

    host4:
        depends_on:
            - reverseproxy
        # image: httpd:alpine
        # image: quay.io/whoacademy/virtual-learning-assistant
        # command: ./bp -p
        build: ./bot
        # mem_limit: 512m
        # mem_reservation: 128M
        # cpus: 1
        restart: always

    host4:
        depends_on:
            - reverseproxy
        # image: httpd:alpine
        # image: quay.io/whoacademy/virtual-learning-assistant
        # command: ./bp -p
        build: ./bot
        # mem_limit: 512m
        # mem_reservation: 128M
        # cpus: 1
        restart: always

    # host5:
    #     depends_on:
    #         - reverseproxy
    #     # image: httpd:alpine
    #     # image: quay.io/whoacademy/virtual-learning-assistant
    #     # command: ./bp -p
    #     build: ./bot
    #     # mem_limit: 512m
    #     # mem_reservation: 128M
    #     # cpus: 1
    #     restart: always

    # host6:
    #     depends_on:
    #         - reverseproxy
    #     # image: httpd:alpine
    #     # image: quay.io/whoacademy/virtual-learning-assistant
    #     # command: ./bp -p
    #     build: ./bot
    #     # mem_limit: 512m
    #     # mem_reservation: 128M
    #     # cpus: 1
    #     restart: always


    # host7:
    #     depends_on:
    #         - reverseproxy
    #     # image: httpd:alpine
    #     # image: quay.io/whoacademy/virtual-learning-assistant
    #     # command: ./bp -p
    #     build: ./bot
    #     # mem_limit: 512m
    #     # mem_reservation: 128M
    #     # cpus: 1
    #     restart: always

    # host8:
    #     depends_on:
    #         - reverseproxy
    #     # image: httpd:alpine
    #     # image: quay.io/whoacademy/virtual-learning-assistant
    #     # command: ./bp -p
    #     build: ./bot
    #     # mem_limit: 512m
    #     # mem_reservation: 128M
    #     # cpus: 1
    #     restart: always